### ISSUE TITLE
Empty Employee List

### ISSUE THREAD

**Issue by alvinlb** [exo-addons/rh-requests-management#1]
Leave request works, but I can't see a way to assign a leave policy (amount of days) to a user/member.  I can see requests in the requests list, but employee list is empty.

Am I missing something?

**Comment by mkrout** [comment]
Hi, can you please attach some screenshots to clarify your need?

**Comment by alvinlb** [comment]
Hi mkrout.

Users can submit requests and have them approved. The user can see a history of their requests, but I can find no way to apply a balance of leaves to each user, therefore nothing appears in the balance history. Also the employee list is empty.

![balance history](https://user-images.githubusercontent.com/1862170/52426724-69fcb000-2af6-11e9-9869-7e02f3e6b367.png)
![employee list](https://user-images.githubusercontent.com/1862170/52426725-69fcb000-2af6-11e9-9093-253b5f79fb23.png)
![request list](https://user-images.githubusercontent.com/1862170/52426726-69fcb000-2af6-11e9-98e9-c027d0e28657.png)

**Comment by mkrout** [comment]
Ok, you need to 

- Add  a space named "exo_employees" (unfortunately its harcoded now, but it should be customizable in coming version)
- Add all users that will be able to create requests to the space.
- Go to the employees admin page and use the find users field to select users:
![1 hr employees administration](https://user-images.githubusercontent.com/1576267/52432888-fc5b7e80-2b0b-11e9-9da0-5c008224628a.png)
- Now you can add users RH information

**Comment by alvinlb** [comment]
Fantastic, thanks very much mkrout.

Looking forward to seeing the coming version!

**Comment by mkrout** [comment]
You're welcome,
Don't hesitate if you have any question or feedback.
